import React from "react";
import { LegalLayout, LegalSection } from "@/components/LegalLayout";

export default function Disclaimer() {
  const sections: LegalSection[] = [
    {
      id: "no-legal-advice",
      title: "1. No Legal Advice Notice",
      content: (
        <>
          <p className="font-semibold text-red-600 dark:text-yellow-500">
            DISCLAIMER: INFORMATION IS NOT LEGAL ADVICE
          </p>
          <p>
            All information, text, outputs, chat conversations, analysis, case summaries, drafts, templates, and reference materials available on or through Dastavez AI (the "Platform") are provided for <strong>general informational and educational purposes only</strong>.
          </p>
          <p>
            No information contained on this Platform should be construed as legal advice or an attempt to practice law. The law is dynamic, regional, and highly dependent on specific details. The materials and information here may not reflect the most current legal developments, judgments, or modifications to local statutes.
          </p>
        </>
      ),
    },
    {
      id: "no-attorney-client-relationship",
      title: "2. No Attorney-Client Relationship",
      content: (
        <>
          <p>
            Your access to, use of, or interaction with Dastavez AI or its AI models does not create, establish, or constitute an <strong>attorney-client relationship</strong> between you and Doclair Dastavez AI Solution Private Limited, its employees, representatives, or developers.
          </p>
          <p>
            Communications through the Platform are not protected by attorney-client privilege or the work-product doctrine. Therefore, you should not upload or send highly sensitive or confidential information that you would expect to be protected under such privilege.
          </p>
        </>
      ),
    },
    {
      id: "ai-output-limitations",
      title: "3. AI Output Limitations",
      content: (
        <>
          <p>
            Dastavez AI utilizes generative artificial intelligence, neural networks, and automated semantic indices to scan, summarize, and assist with document workflows. You acknowledge and agree that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Accuracy & Hallucinations:</strong> Generative models are subject to "hallucinations" or errors where they may synthesize legal statements or case references that are inaccurate, obsolete, or incorrect.</li>
            <li><strong>Lack of Nuance:</strong> AI cannot replicate the judgment, strategic reasoning, and nuanced understanding of a qualified lawyer.</li>
            <li><strong>No Certification:</strong> AI outputs are not vetted, approved, or certified by any judicial body, court, bar association, or attorney.</li>
          </ul>
        </>
      ),
    },
    {
      id: "user-responsibility",
      title: "4. User Responsibility",
      content: (
        <>
          <p>
            You are <strong>solely responsible</strong> for how you use and rely on the outputs, templates, and summaries generated by the Platform:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Verification:</strong> You must independently verify all statutory citations, case laws, clauses, and drafts generated by the AI before using them in any transaction, court proceeding, or binding agreement.</li>
            <li><strong>Professional Consultation:</strong> We strongly advise that you consult with a licensed attorney or qualified legal professional in your jurisdiction before making any legal decisions.</li>
            <li><strong>Assumption of Risk:</strong> Any reliance on the outputs of the Platform is entirely at your own risk. We assume no liability for errors, omissions, or actions taken based on our AI recommendations.</li>
          </ul>
        </>
      ),
    },
    {
      id: "contact-information",
      title: "5. Contact Information",
      content: (
        <>
          <p>
            If you need to contact us regarding the terms of this Disclaimer or need professional clarification on how Dastavez AI functions, please contact us:
          </p>
          <div className="bg-gray-50 dark:bg-judicial-navy/30 border border-gray-100 dark:border-judicial-gold/10 p-6 rounded-xl mt-4">
            <p className="font-semibold text-black dark:text-white">Doclair Dastavez AI Solution Private Limited</p>
            <p className="text-gray-600 dark:text-gray-400 mt-2">Patna, Bihar, India</p>
            <p className="text-gray-600 dark:text-gray-400">Email: <a href="mailto:info@dastavezai.org" className="text-judicial-gold hover:underline">info@dastavezai.org</a></p>
            <p className="text-gray-600 dark:text-gray-400">Phone: <a href="tel:+918210607476" className="text-judicial-gold hover:underline">+91 8210607476</a></p>
          </div>
        </>
      ),
    },
  ];

  return (
    <LegalLayout
      title="Legal Disclaimer"
      subtitle="Please read this Legal Disclaimer carefully. Dastavez AI is an automated platform and does not provide legal counsel."
      lastUpdated="June 19, 2026"
      metaTitle="Legal Disclaimer"
      metaDescription="Read the Dastavez AI legal disclaimer. AI outputs are informational only, do not constitute legal advice, and do not create an attorney-client relationship."
      sections={sections}
    />
  );
}
